[package]
name = "full_lion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
square_reed_solomon = { path = "../square_reed_solomon"}